//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMO
    {
        public int ID { get; set; }
        public int CODIGO_ESTUDIANTE { get; set; }
        public int ID_LIBRO { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual ESTUDIANTES ESTUDIANTES { get; set; }
        public virtual LIBROS LIBROS { get; set; }
    }
}
